param(
  [string]$SshConfigPath = "$HOME\.ssh\config",
  [string]$CoderConfigSshPath = "$HOME\.ssh\coder-config-ssh",
  [string]$AliasFilePath = "$HOME\.ssh\codex-coder-aliases",
  [string]$Owner = "voarsh",
  [string]$AliasPrefix = "coder"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-CoderConfig {
  param([string]$ConfigPath)

  if (-not (Test-Path -LiteralPath $ConfigPath)) {
    throw "SSH config not found: $ConfigPath"
  }

  $lines = Get-Content -LiteralPath $ConfigPath
  $hostLine = $lines | Where-Object { $_ -match '^Host\s+coder-vscode\..+--\*$' } | Select-Object -First 1
  if (-not $hostLine) {
    throw "Could not find the VS Code-managed Coder wildcard host block in $ConfigPath"
  }

  $proxyLine = $lines | Where-Object { $_ -match '^\s+ProxyCommand\s+' } | Select-Object -First 1
  if (-not $proxyLine) {
    throw "Could not find ProxyCommand in $ConfigPath"
  }

  if ($hostLine -notmatch '^Host\s+(?<pattern>.+\*)$') {
    throw "Could not parse wildcard host pattern from line: $hostLine"
  }

  $hostPattern = $Matches.pattern
  $hostPrefix = $hostPattern.Substring(0, $hostPattern.Length - 1)

  $proxyCommand = $proxyLine -replace '^\s+ProxyCommand\s+', ''
  if ($proxyCommand -notmatch '^"(?<coderBinary>[^"]+)"\s+--global-config\s+"(?<globalConfig>[^"]+)"\s+') {
    throw "Could not parse Coder binary/global config from ProxyCommand: $proxyCommand"
  }

  [pscustomobject]@{
    HostPrefix   = $hostPrefix
    ProxyCommand = $proxyCommand
    CoderBinary  = $Matches.coderBinary
    GlobalConfig = $Matches.globalConfig
  }
}

function Ensure-IncludeLine {
  param(
    [string]$ConfigPath,
    [string]$AliasPath
  )

  $includeLine = "Include ~/.ssh/$([IO.Path]::GetFileName($AliasPath))"
  $raw = if (Test-Path -LiteralPath $ConfigPath) { Get-Content -LiteralPath $ConfigPath -Raw } else { "" }
  $escapedIncludeLine = [regex]::Escape($includeLine)

  if ($raw -match "(?m)^$escapedIncludeLine\s*$") {
    return
  }

  $newRaw = if ([string]::IsNullOrWhiteSpace($raw)) {
    "$includeLine`r`n"
  } else {
    "$includeLine`r`n`r`n$raw"
  }

  Set-Content -LiteralPath $ConfigPath -Value $newRaw -NoNewline
}

function Update-CoderConfigSsh {
  param(
    [string]$CoderBinary,
    [string]$GlobalConfig,
    [string]$CoderConfigSshPath
  )

  & $CoderBinary --global-config $GlobalConfig config-ssh --yes --ssh-config-file $CoderConfigSshPath | Out-Null
}

function New-AliasName {
  param(
    [string]$WorkspaceName,
    [string]$Prefix,
    [hashtable]$SeenAliases
  )

  $base = ($WorkspaceName.ToLowerInvariant() -replace '[^a-z0-9-]+', '-') -replace '-+', '-'
  $base = $base.Trim('-')
  if ([string]::IsNullOrWhiteSpace($base)) {
    $base = "workspace"
  }

  $candidate = "$Prefix-$base"
  $counter = 2
  while ($SeenAliases.ContainsKey($candidate)) {
    $candidate = "$Prefix-$base-$counter"
    $counter++
  }

  $SeenAliases[$candidate] = $true
  return $candidate
}

function Get-WorkspaceNames {
  param(
    [string]$CoderBinary,
    [string]$GlobalConfig
  )

  if (-not (Test-Path -LiteralPath $CoderBinary)) {
    throw "Coder binary not found: $CoderBinary"
  }

  $json = & $CoderBinary --global-config $GlobalConfig list -o json
  if (-not $json) {
    throw "Coder returned no workspace data."
  }

  $workspaces = $json | ConvertFrom-Json
  @($workspaces | Sort-Object name | Select-Object -ExpandProperty name)
}

function Build-AliasFile {
  param(
    [string[]]$WorkspaceNames,
    [string]$CoderBinary,
    [string]$GlobalConfig,
    [string]$AliasPrefix
  )

  $seenAliases = @{}
  $lines = New-Object System.Collections.Generic.List[string]

  $timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
  $lines.Add("# Concrete Coder workspace aliases for Codex discovery.")
  $lines.Add("# Generated by sync-coder-codex-aliases.ps1 on $timestamp.")
  $lines.Add("")

  foreach ($workspace in $WorkspaceNames) {
    $alias = New-AliasName -WorkspaceName $workspace -Prefix $AliasPrefix -SeenAliases $seenAliases
    $lines.Add("Host $alias")
    $lines.Add("  HostName $workspace.coder")
    $lines.Add("  User admin")
    $lines.Add("  ConnectTimeout 0")
    $lines.Add("  LogLevel ERROR")
    $lines.Add("  ProxyCommand `"$CoderBinary`" --global-config `"$GlobalConfig`" ssh --stdio $workspace")
    $lines.Add("  SetEnv CODER_SSH_SESSION_TYPE=codex")
    $lines.Add("  StrictHostKeyChecking no")
    $lines.Add("  UserKnownHostsFile /dev/null")
    $lines.Add("")
  }

  return ($lines -join "`r`n").TrimEnd() + "`r`n"
}

$coderConfig = Get-CoderConfig -ConfigPath $SshConfigPath
$workspaceNames = Get-WorkspaceNames -CoderBinary $coderConfig.CoderBinary -GlobalConfig $coderConfig.GlobalConfig

$aliasDirectory = [IO.Path]::GetDirectoryName($AliasFilePath)
if (-not (Test-Path -LiteralPath $aliasDirectory)) {
  New-Item -ItemType Directory -Path $aliasDirectory | Out-Null
}

Update-CoderConfigSsh `
  -CoderBinary $coderConfig.CoderBinary `
  -GlobalConfig $coderConfig.GlobalConfig `
  -CoderConfigSshPath $CoderConfigSshPath

Ensure-IncludeLine -ConfigPath $SshConfigPath -AliasPath $CoderConfigSshPath
Ensure-IncludeLine -ConfigPath $SshConfigPath -AliasPath $AliasFilePath

$aliasContent = Build-AliasFile `
  -WorkspaceNames $workspaceNames `
  -CoderBinary $coderConfig.CoderBinary `
  -GlobalConfig $coderConfig.GlobalConfig `
  -AliasPrefix $AliasPrefix

Set-Content -LiteralPath $AliasFilePath -Value $aliasContent -NoNewline

Write-Host "Synced $($workspaceNames.Count) Coder workspace aliases to $AliasFilePath"
